"""Added accepted column to JoinRequest

Revision ID: 0c28d35a59a1
Revises: 
Create Date: 2024-04-08 16:51:14.781464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c28d35a59a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('join_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accepted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('join_request', schema=None) as batch_op:
        batch_op.drop_column('accepted')

    # ### end Alembic commands ###
